### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/tuning-workbench-synth#10] opened 2020-02-27 17:49 UTC
#1 About, Export, Load SCL appear to be dead; however dragging dropping works
#2 pitch bend maxes at 10
#3 Reset button works however the Apply SCL/KBM do not appear to

**Comment by baconpaul** [comment] 2020-02-27 17:53
Your first item is #6 
Your second is #4 
but I don't understand your third. Why doesn't the button work?

**Comment by baconpaul** [comment] 2020-02-27 17:55
Confirmed on slack that the third is deactivating due to edits and stuff and it's all cool so closing this one as dups.

Thanks!!

**Closed as completed by baconpaul** 2020-02-27 17:55 UTC
